FROM openjdk:8-jdk-alpine
MAINTAINER qingbao.ho@gmail.com

COPY build/libs/weather-collection-service-1.0.jar /weather-collection-service.jar
ENTRYPOINT ["java", "-jar", "/weather-collection-service.jar"]